### ISSUE TITLE
Total price shows NaN on Shopping list

### ISSUE THREAD

**Issue by eericn** [gigapath/whatthefridge#133] opened 2015-10-06 00:37 UTC

**Comment by josh-stevens** [comment] 2015-10-06 00:41
I've been unable to reproduce this bug. If anyone runs into this problem again, please give me as much information as possible. What did you click on? What did you change? What was the value of the price field before the NaN showed up, and what did you change it to that made NaN show up? Try to log as much info as possible.

**Comment by josh-stevens** [comment] 2015-10-08 17:06
This has been taken care of on my branch for recipes on lists, so that merge will close this issue

**Closed as completed** 2015-10-08 20:32 UTC
Labels: bug
